include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"
    - "test/**"
  errors:
    deprecated_member_use: ignore

linter:
  rules:
    avoid_print: false
    use_build_context_synchronously: false
    unnecessary_brace_in_string_interps: false
    avoid_relative_lib_imports: false
    use_super_parameters: false
    avoid_shadowing_type_parameters: false
    unintended_html_in_doc_comment: false
    unnecessary_underscores: false
    sized_box_for_whitespace: false
    deprecated_member_use_from_same_package: false