// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjepMLtfF2PAJknHdKISIP93H92hwtrdk',
    appId: '1:285822024847:web:4129c7ffb7b05b916e44fa',
    messagingSenderId: '285822024847',
    projectId: 'tego-d918b',
    authDomain: 'tego-d918b.firebaseapp.com',
    storageBucket: 'tego-d918b.firebasestorage.app',
    measurementId: 'G-DR6SG68T9T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuXNJ4GCpLttFxtC49QNHhX1Zli-hY9os',
    appId: '1:285822024847:android:811149d88011f30a6e44fa',
    messagingSenderId: '285822024847',
    projectId: 'tego-d918b',
    storageBucket: 'tego-d918b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARv-AbYJyP9Ns3U4PVzQnJQJ5U5Xe19eA',
    appId: '1:285822024847:ios:eef23662c9df12816e44fa',
    messagingSenderId: '285822024847',
    projectId: 'tego-d918b',
    storageBucket: 'tego-d918b.firebasestorage.app',
    iosClientId: '285822024847-gbv283uq32oep4gu27vghctk58oecq71.apps.googleusercontent.com',
    iosBundleId: 'com.example.tego',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARv-AbYJyP9Ns3U4PVzQnJQJ5U5Xe19eA',
    appId: '1:285822024847:ios:eef23662c9df12816e44fa',
    messagingSenderId: '285822024847',
    projectId: 'tego-d918b',
    storageBucket: 'tego-d918b.firebasestorage.app',
    iosClientId: '285822024847-gbv283uq32oep4gu27vghctk58oecq71.apps.googleusercontent.com',
    iosBundleId: 'com.example.tego',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjepMLtfF2PAJknHdKISIP93H92hwtrdk',
    appId: '1:285822024847:web:19e999f3551731826e44fa',
    messagingSenderId: '285822024847',
    projectId: 'tego-d918b',
    authDomain: 'tego-d918b.firebaseapp.com',
    storageBucket: 'tego-d918b.firebasestorage.app',
    measurementId: 'G-1KK3NFZ16S',
  );
}
